version: '3.7'

services:
    server:
        build: .
        volumes:
            - ../etc/nginx/sites-available:/etc/nginx/sites-available
            - ../etc/nginx/ssl:/etc/nginx/ssl
            - mysql-storage:/var/lib/mysql
            - sites-volumes:/var/www
        ports:
            - '80:80'
            - '443:443'
            - '3306:3306'
            # - '5173:5173'
            # - '8080:8080'
            # - '8090:8090'
        extra_hosts:
            - localhost:127.0.0.1
            - perakit.test:127.0.0.1
        environment:
            MYSQL_ROOT_PASSWORD: [Enter_root_password]
            MYSQL_DATABASE: [Enter_database_name]
            MYSQL_USER: [Enter_user_name]
            MYSQL_PASSWORD: [Enter_user_password]
volumes:
    mysql-storage:
    sites-volumes:
