version: '3.7'

services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx.podmanfile
        depends_on:
            - php
            - nodejs
            - mysql
        volumes:
            - ../www:/var/www
            - ../etc/nginx/sites-available:/etc/nginx/sites-available
            - ../etc/nginx/ssl:/etc/nginx/ssl
            - sites-volumes:/var/volumes
        ports:
            - '80:80'
            # - '443:443'
            # - '8080:8080'
            # - '8090:8090'
        extra_hosts:
            - localhost:127.0.0.1
            # - laravel.test:127.0.0.1
        working_dir: /var/www
        networks:
            perakit_network:
                # ipv4_address: 172.18.0.1
    php:
        build:
            context: .
            dockerfile: ./phpfpm.podmanfile
            # dockerfile: ./phpfpm-xdebug.podmanfile
        volumes:
            - ../www:/var/www
            - ../etc/php/alpine-fpm-pool:/etc/php83/php-fpm.d
            # - ../etc/php/conf.d/xdebug.ini:/etc/php83/conf.d/docker-php-ext-xdebug.ini
            # - ../etc/php/conf.d/error_reporting.ini:/etc/php83/conf.d/error_reporting.ini
            - sites-volumes:/var/volumes
        working_dir: /var/www
        ports:
            - '9000:9000'
            # - '9001:9001'
        networks:
            perakit_network:
                # ipv4_address: 172.18.0.2
    nodejs:
        build:
            context: .
            dockerfile: ./nodejs.podmanfile
        volumes:
            - ../www:/var/www
            - sites-volumes:/var/volumes
        working_dir: /var/www
        # ports:
        #     - '5173:5173'
        networks:
            perakit_network:
                # ipv4_address: 172.18.0.3
    mysql:
        build:
            context: .
            dockerfile: ./mariadb.podmanfile
        environment:
            MYSQL_ROOT_PASSWORD: [Enter_root_password]
            MYSQL_DATABASE: [Enter_database_name]
            MYSQL_USER: [Enter_user_name]
            MYSQL_PASSWORD: [Enter_user_password]
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql-storage:/var/lib/mysql
        restart: always
        networks:
            perakit_network:
                # ipv4_address: 172.18.0.5
volumes:
    mysql-storage:
    sites-volumes:
networks:
    perakit_network:
        name: perakit_network
        driver: bridge
        # ipam:
        #     driver: default
        #     options:
        #         driver: host-local
        #     config:
        #         - subnet: 172.18.0.0/16
