version: '3.7'

services:
    server:
        build: .
        volumes:
            - ./www:/var/www
            - ./etc/nginx/sites-available:/etc/nginx/sites-available
            - ./etc/nginx/ssl:/etc/nginx/ssl
            - ./etc/php/php-fpm.d:/etc/php83/php-fpm.d
            - mysql-storage:/var/lib/mysql
            - sites-volumes:/var/volumes
        ports:
            - '80:80'
            # - '443:443'
            - '3306:3306'
            # - '5173:5173'
            # - '8080:8080'
            # - '8090:8090'
        extra_hosts:
            - localhost:127.0.0.1
            # - laravel.test:127.0.0.1
        working_dir: /var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: [Enter_root_password]
            MYSQL_DATABASE: [Enter_database_name]
            MYSQL_USER: [Enter_user_name]
            MYSQL_PASSWORD: [Enter_user_password]
volumes:
    mysql-storage:
    sites-volumes:
